# Generated by Django 3.2.12 on 2022-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='avatar.jpg', upload_to='color_upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload_Image',
        ),
    ]
