# Generated by Django 3.2.12 on 2022-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_document_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('photo', models.ImageField(default='d.jpg', upload_to='color_upload/')),
            ],
        ),
        migrations.CreateModel(
            name='RestoreUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('photo', models.ImageField(default='d.jpg', upload_to='restore_upload/')),
            ],
        ),
        migrations.CreateModel(
            name='StyleUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('photo', models.ImageField(default='d.jpg', upload_to='style_upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploader',
        ),
        migrations.AddField(
            model_name='member',
            name='upload_color_img',
            field=models.ImageField(default='d.jpg', upload_to='style_upload/'),
        ),
        migrations.AddField(
            model_name='member',
            name='upload_restore_img',
            field=models.ImageField(default='d.jpg', upload_to='restore_upload/old/'),
        ),
        migrations.AddField(
            model_name='member',
            name='upload_style_img',
            field=models.ImageField(default='d.jpg', upload_to='style_upload/'),
        ),
    ]
